/*
 * Masrik Dahir
 * Date: 02/20/2022
 * This program runs on the server side and conpute the median 
 * of the *input
 * 
 *
 * Usage Guide (First Terminal- Server)
 * (1) make
 * (2) ./avg_svc
 * Usage Guide (Second Terminal- Client)
 * (1) ./ravg 127.0.0.1 <numbers seperated by single space>
 */

#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
/* run locally on 'server' called by a remote client. */
static double sum_avg;
/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */

// comparator functions for qsort
// ascending sort 
int comp_ascending (const void * a, const void * b) {       
    if (*(double*)a > *(double*)b) {
      return 1;
    }
    else if (*(double*)a < *(double*)b) {
      return -1;
    }
    else 
      return 0;
}

double * average_1(input_data *input, CLIENT *client) 
  {
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;
  qsort(dp,input->input_data.input_data_len,sizeof(double),comp_ascending);
  u_int i;
  sum_avg = 0;
  double arr[input->input_data.input_data_len];
  /* iterate until end of number of times (data_len) */
  for( i = 0; i <= input->input_data.input_data_len-1; i++ )
    {
    arr[i] = *dp;
    dp++;
    }

  int size = sizeof(arr) / sizeof(arr[0]);
  if (input->input_data.input_data_len % 2 == 0){
    sum_avg = ((double) arr[(input->input_data.input_data_len/2)-1] + arr[input->input_data.input_data_len/2])/2;
  }
  else{
    sum_avg = arr[((input->input_data.input_data_len +1)/2)-1];
  }

  return( &sum_avg );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }