/*
 * Masrik Dahir
 * Date: 02/20/2022
 * This program runs on the server side. It returns the ascending or 
 * descending sort of the client *input
 * 
 *
 * Usage Guide (First Terminal- Server)
 * (1) make
 * (2) ./avg_svc
 * Usage Guide (Second Terminal- Client)
 * (1) ./ravg 127.0.0.1 <numbers seperated by single space>
 */

#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include <stdlib.h>

/* run locally on 'server' called by a remote client. */
static double sum_avg;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */

// comparator functions for qsort
// ascending sort 
int comp_ascending (const void * a, const void * b) {       
    if (*(double*)a > *(double*)b) {
      return 1;
    }
    else if (*(double*)a < *(double*)b) {
      return -1;
    }
    else 
      return 0;
}
// descending sort
int comp_descending (const void * a, const void * b) {       
    if (*(double*)a < *(double*)b) return 1;
    else if (*(double*)a > *(double*)b) return -1;
    else return 0;
}

input_data * average_1(input_data *input, CLIENT *client) {
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  double option = (double)input->input_data.input_data_val[0];

  dp++;

  if ((int)option == 0){
    qsort(dp,input->input_data.input_data_len - 1,sizeof(double),comp_ascending);
    
  }
  else if (option == 1){
    qsort(dp,input->input_data.input_data_len - 1,sizeof(double),comp_descending);
  }

  return( input );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data * average_1_svc(input_data *input, struct svc_req *svc) {
  CLIENT *client;
  return( average_1( input, client) );
}

